### ISSUE TITLE
Cannot find guardian's stats

### ISSUE THREAD

**Issue by pylaligand** [slavikus/guardiangg-bot#1]
This is in Slack:

```
/elo ScrubsKip
Guardian.GG BOT [6:42 PM] 
Sorry, ​*ScrubsKip*​ was not found.
```

I tried sending (manually) the same requests to bungie.net as lookup_user in common.inc.php and I get some results:

```
https://www.bungie.net/platform/destiny/SearchDestinyPlayer/2/ScrubsKip

{
    "ThrottleSeconds": 0,
    "Message": "Ok",
    "Response": [
        {
            "displayName": "ScrubsKip",
            "membershipId": "4611686018437314658",
            "iconPath": "/img/theme/destiny/icons/icon_xbl.png",
            "membershipType": 1
        }
    ],
    "ErrorStatus": "Success",
    "ErrorCode": 1,
    "MessageData": {

    }
}
```

Yet looking at the code it seems that lookup_user decides to return null for this user, not sure why or how.
Interestingly, this user seems to have accounts on both platforms - maybe this helps.

Side note: great work on these bots!

**Comment by slavikus** [comment]
Weirdly enough, it does looks up player ID, but then guardian.gg fails to fetch data (even on the web site, try looking it up yourself - http://guardian.gg/en/profile/1/scrubskip/5 ). Probably @spiffyjr needs to look into it?..

**Comment by spiffyjr** [comment]
I'm seeing the character okay?

**Comment by slavikus** [comment]
Hey @spiffyjr, thank you for stopping by!

I do see the data on the web site, but the API returns an empty array for some reason -- https://api.guardian.gg/elo/4611686018429235498

Bungie.Net seem to return valid profile -- https://www.bungie.net/en/Profile/2/4611686018429235498

Any ideas what's going on?

TIA!

**Comment by spiffyjr** [comment]
Have they played recently? I'm not showing any data for that player...

**Comment by pylaligand** [comment]
They haven't played since 2/25.

**Comment by pylaligand** [comment]
Likely obsolete.
